engines:
  shellcheck:
    enabled: true
  duplication:
    enabled: true
ratings:
   paths:
   - "swagger-example/**"
   - "async-support-example/**"
   - "spring-security-example/**"
   
   exclude_paths:
- swagger-example/src/main/resources/static/dist/lib/
